set -g default-terminal  "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows when one is closed
set -g renumber-windows on

# bind keys
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# vim keys 
set-window-option -g mode-keys vi

# splits
unbind %
unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# vim navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim with opt key
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# reload config
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
#set -g @plugin 'theutz/tmux-tokyonight-nvim' // Nice tokyonight alternatived based on lazyvim. 
#set -g @plugin 'capuccin/tmux#v2.1.3' // Nice catpuccin bar, like omerxx

# Tokyo Night theme
set -g @tokyo-night-tmux_theme night   # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 (true) or 0 (false)
#set -g @tokyo-night-tmux_window_id_style digital
#set -g @tokyo-night-tmux_pane_id_style hsquare
#set -g @tokyo-night-tmux_zoom_id_style dsquare
# Icon styles
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 

# No extra spaces between icons
set -g @tokyo-night-tmux_window_tidy_icons 0

# time and date widget
set -g @tokyo-night-tmux_show_datetime 0
set -g @tokyo-night-tmux_date_format MDY
set -g @tokyo-night-tmux_time_format 12H

# now playing widget
set -g @tokyo-night-tmux_show_music 1

# netspeed widget
set -g @tokyo-night-tmux_show_netspeed 1
set -g @tokyo-night-tmux_show_netspeed_iface "wlan0" # Detected via default route
set -g @tokyo-night-tmux_show_netspeed_showip 1 # display ipv4 address
set -g @tokyo-night-tmux_show_netspeed_refresh 1 # update interval in seconds

# battery widget 
#set -g @tokyo-night-tmux_show_battery_widget 1
#set -g @tokyo-night-tmux_show_battery_name "BAT1" # Some linux distros have
#set -g @tokyo-night-tmux_show_low_threshold 21 # default 

# Hostname
set -g @tokyo-night-tmux_show_hostname 0 # off 1 for on.

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
run '~/.tmux/plugins/tpm/tpm'

